### ISSUE TITLE
publish version to PyPI for <= Python 3.5

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#237]
**Describe the bug**
When users run `pip install pipx` with anything < Python 3.6, they will get the old pipx package, which is not related to this one. It is completely different, and very confusing that this occurs. Noted in https://twitter.com/mgedmin/status/1183682386103558144.

**How to reproduce**
Run
```
python3.5 -m pip install pipx
pipx --help
```

**Expected behavior**
An error should occur at install time saying that pipx is only supported for 3.6+. 

Removing the bad versions from PyPI is not a good idea since others may be depending on that package still.

**Comment by AlJohri** [comment]
As a temporary measure,  I'd advocate for removing the old versions altogether since the old package can still be installed via [git](https://github.com/khalti/pipx) if someone needs. The old package is a development dependency (cli tool) and removal from PyPI very likely shouldn't break any production code. There seems to be a few people, presumably mistakenly, installing the package on python < 3.6 every day: https://pypistats.org/packages/pipx

A version can be uploaded at a later date that shows an error post-install.

**Comment by gaborbernat** [comment]
I would caution against removing, but rather release a patch that raises as suggested from the old tag.

**Comment by cs01** [comment]
Agreed, removing is a bad idea since it breaks people's workflows. I won't be doing that. Also of note, npm does not allow it at all. They require you transfer ownership of your packages to them if you try to delete your account.
