### ISSUE TITLE
pipx package overrides virtual environment 

### ISSUE THREAD

**Issue by zachvalenta** [pipxproject/pipx#272]
I have a project that has `bpython` installed as a dev dependency. 

I also have `bpython` installed by pipx. 

When I'm inside an active virtual environment, I would have thought that opening a `bpython` REPL would use the version of `bpython` scoped to my project's `venv/bin/python3` but instead pipx's version is overriding it.

**Comment by itsayellow** [comment]
This sounds like it may not be a pipx issue.  I'm guessing it comes down to the order of directories in your PATH environment variable.

First run `which bpython` to verify which bpython you are executing.  It should be the one in `venv/bin`.

Then you can check the value of your PATH environment variable with `echo $PATH` (or if you are on Windows I believe it is `echo %PATH%`.  The `venv/bin/` directory in your activated virtual environment should be first, and before the pipx bin directory `~/.local/bin`.  If it is not the case then this will cause you to run the pipx bpython when just typing `bpython`.

You can make sure you run your venv bpython by choosing it specifically by running `venv/bin/bpython` instead of just `bpython`.

If you are running the `bpython` of `venv/bin/bpython` and you are getting the wrong python then something else is going on as to what bpython itself is doing.

**Comment by zachvalenta** [comment]
`which bpython` in the venv pointed to `~/.local/bin/bpython` (i.e. pipx)

I managed to iron it out by uninstalling (`pipx uninstall bpython`) and then reinstalling (`pipx install bpython`). After this running `bpython` inside my activated venv pointed to the venv-local `bpython`.

**Comment by zachvalenta** [comment]
Also, thanks for the long and helpful response :) 👍🏼
