### ISSUE TITLE
Trouble installing local wheel file

### ISSUE THREAD

**Issue by KeenanKunzelman** [pipxproject/pipx#352]
Below is my setup.py file. I am fairly new to packaging python so sorry if this is an error on my end. I run `python3 setup.py bdist_wheel` and I get my .whl file. I tried to run `pipx install  qualpy-1.0.0-py3-none-any.whl` and I would get a `Cannot determine package name from spec 'qualpy-0.0.1-py3-none-any.whl'. Check package spec for errors.` error. I then did some research and saw cs01 [suggesting](https://github.com/pipxproject/pipx/issues/216) to use the --spec flag. I tried to use it but now I just get a `pipx: error: unrecognized arguments: --spec`. Some guidance would be greatly appreciated 😄.

```python
import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="qualpy",
    version="1.0.0",

    packages=setuptools.find_packages(),

    python_requires='>=3.6',
    entry_points={
        'console_scripts': [
            'qualpy=test_package.qualpy:main'
        ]
    }
)
```

**Comment by uranusjr** [comment]
pipx can’t tell whether you intend a name like this to be a filename or package name. Give it some hints: `pipx install ./ qualpy-1.0.0-py3-none-any.whl`

**Comment by cs01** [comment]
I think it has something to do with pip trying to install something other than the .whl file when you are in a directory with the same name as the package. Are you in a directory named `qualpy ` when running `pipx`? Try going up a directory and re-running, updating the path to the .whl file accordingly.

**Comment by KeenanKunzelman** [comment]
Ahhhh I see the issue was what you thought cs01. I created a package that was actually called test_dir to test out pipx but forgot to change the name in setup.py to reflect this. I changed the name and it worked like a charm! Thank you so much for the quick reply!

**Comment by cs01** [comment]
@uranusjr  Looks like `pip list` changes its output based on if you are in a directory with `setup.py` (and probably pyproject.toml?). This affects pipx's logic of determining a package's name. We should probably add a warning or error to pipx if the current working directory has something that affects `pip list`. (cc @itsayellow)

**Comment by KeenanKunzelman** [comment]
@uranusjr and @cs01 can confirm I was in a directory with setup.py.

**Comment by itsayellow** [comment]
btw @KeenanKunzelman, the `--spec` argument was for an older version of pipx, that's why it didn't work this time.  It has been removed and now you can type either a spec or a package name without needing that command-line switch.

I'm not exactly following what happened with the package name being called `test_dir`, that might have some bearing on this.  (Was it just a problem with the wheel?)

As to the `pip list` and `setup.py` I'd be curious to get more information on that.  I couldn't find anything on it by googling.  This (https://pip.pypa.io/en/stable/reference/pip_install/#argument-handling) seems to indicate that if you pass a wheel file in, pip should install that wheel and not parse the directory.  This  (https://pip.pypa.io/en/stable/reference/pip_list/) doesn't mention setup.py in connection with `pip list`.

**Comment by itsayellow** [comment]
@KeenanKunzelman, always the easiest way to help us understand if it's a problem specific to pipx, is: Does what you're trying to install work with plain `pip`?

**Comment by KeenanKunzelman** [comment]
@itsayellow @cs01 @uranusjr  Thanks for the feedback! It was an issue with how I was building the wheel file. Still a total noob at using setuptools. After doing some testing I can confirm the real issue was that when I ran `python3 setup.py bdist_wheel` setup.py's name attribute was assigned `qualpy` but the parent directory was named `test_dir`. Thanks for all your help and for writing this awesome tool! I hope to help contribute towards pipx more in the future 😄.
