### ISSUE TITLE
 include the pipx version when the --verbose flag is passed

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#423]
**How would this feature be useful?**

Version will be available in bug reports without running a separate command

**Describe the solution you'd like**

User logger to log the version

**Describe alternatives you've considered**

**Comment by spazm** [comment]
Feature discussion questions:
* What log level?  I'd default to assuming INFO
* Is it ok to log the version even if the arg parser is going to fail due to invalid command argument?

I see the two likely options as logging this as late as possible, just before the if-else chain on args.command in run_pipx_command or to run much earlier, in the cli entrypoint, just after parsing the args.

**Comment by itsayellow** [comment]
Typically pipx logs to INFO to put things in `--verbose` output and not in non-verbose output, as you seem to have gathered.

I don't think we need to worry about the case where the arg parser is going to fail, IMO it could be after that.

`setup()` sounds good to me.

BTW, we the pipx project squashes all the commits in a PR into one commit on merge, so you don't need to worry about cleaning up your own commits or rebasing.
