### ISSUE TITLE
Installing VCS URL should not use `--editable` option

### ISSUE THREAD

**Issue by itsayellow** [pipxproject/pipx#438]
**Describe the bug**

Our package name detection scheme depends on installing a package first with pip and querying its name.  pip seems to allow installation with a bare VCS url **ONLY** if the `--editable` flag is not present.  If the `--editable` flag is present, then pip seems to require the suffix `#egg=<package_name>`.

**How to reproduce**

Using a git package from another issue I was reading (#148) and trying to reproduce:

```
birchtree:pipx pipx install --verbose --editable git+https://github.com/raxod502/diary-manager
pipx > (run_subprocess:112): running /usr/local/opt/python@3.8/bin/python3.8 -m venv --without-pip /var/folders/gp/7z0mcw717y1b0kt0swc1lfp80000gn/T/tmp_5cntfli
pipx > (run_subprocess:112): running /var/folders/gp/7z0mcw717y1b0kt0swc1lfp80000gn/T/tmp_5cntfli/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /Users/mclapp/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /var/folders/gp/7z0mcw717y1b0kt0swc1lfp80000gn/T/tmp_5cntfli/bin/python --version
pipx > (run_subprocess:112): running /var/folders/gp/7z0mcw717y1b0kt0swc1lfp80000gn/T/tmp_5cntfli/bin/python -m pip list --format=json
pipx > (run_subprocess:112): running /var/folders/gp/7z0mcw717y1b0kt0swc1lfp80000gn/T/tmp_5cntfli/bin/python -m pip install --no-dependencies --editable git+https://github.com/raxod502/diary-manager
ERROR: Could not detect requirement name for 'git+https://github.com/raxod502/diary-manager', please specify one with #egg=your_package_name
pipx > (install_package_no_deps:221): '/var/folders/gp/7z0mcw717y1b0kt0swc1lfp80000gn/T/tmp_5cntfli/bin/python -m pip install --no-dependencies --editable git+https://github.com/raxod502/diary-manager' failed
Cannot determine package name from spec 'git+https://github.com/raxod502/diary-manager'. Check package spec for errors.
```

Just with pip itself, `--editable` + VCS URL needs `#egg`:
```
birchtree:pipx pip install --no-dependencies --editable git+https://github.com/raxod502/diary-manager
ERROR: Could not detect requirement name for 'git+https://github.com/raxod502/diary-manager', please specify one with #egg=your_package_name
```
Just with pip itself, bare VCS URL does NOT need `#egg`:
```
birchtree:pipx pip install --no-dependencies git+https://github.com/raxod502/diary-manager 
Collecting git+https://github.com/raxod502/diary-manager
  Cloning https://github.com/raxod502/diary-manager to /private/var/folders/gp/7z0mcw717y1b0kt0swc1lfp80000gn/T/pip-req-build-5kt0mjb7
  Running command git clone -q https://github.com/raxod502/diary-manager /private/var/folders/gp/7z0mcw717y1b0kt0swc1lfp80000gn/T/pip-req-build-5kt0mjb7
Using legacy setup.py install for diary-manager, since package 'wheel' is not installed.
Installing collected packages: diary-manager
    Running setup.py install for diary-manager ... done
Successfully installed diary-manager-2.0.2
```

**Expected behavior**

I expected pip could install the VCS URL whether it was --editable or not.

**Comment by itsayellow** [comment]
I'm not sure if this is an upstream issue, or a known caveat with how `pip install --editable` is supposed to work.

**Comment by itsayellow** [comment]
Oh!  I just realized that this probably has a very easy fix.  Since our first installation of the package to find its name is a temp directory that is discarded, we can simply make sure that installation is non-editable.

**Comment by itsayellow** [comment]
Re-reading pip's documentation, it seems like it may be a semi-documented feature that we don't always need the `#egg=<package_name>` suffix?
https://pip.pypa.io/en/stable/reference/pip_install/#working-out-the-name-and-version
> ...For sdists located via an index, the filename is parsed for the name and project version (this is in theory slightly less reliable than using the egg_info command, but avoids downloading and processing unnecessary numbers of files).
>
>Any URL may use the #egg=name syntax (see VCS Support) to explicitly state the project name.

**Comment by itsayellow** [comment]
I just did some tests:  I can remove `--editable` for package determination, but then it still fails to pip install a bare VCS URL when we try to install it for real with `--editable`.

Maybe this is a wontfix or an upstream, because we are just mirroring a pip behavior.

**Comment by uranusjr** [comment]
This is intentional on pip’s side. `--editable` on a VCS URL needs to be cloned to a predicatable location, and `#egg=` is needed to name the directory. VCS without `--editable` is cloned to a temp directory and purged after installation, so the restriction is not necessary.

For pipx, I’d suggest either reject this combination altogether (considering pipx tends to treat virtual environments it manages as an implementation detail), or simply treats this kind of installation as non-editable.

**Comment by itsayellow** [comment]
I guess I never fully understood what `--editable` with a VCS URL did.

Is the only difference between VCS vs VCS+editable that in the `--editable` case the venv gets an editable `src/` subdirectory?

If so, then I agree, this should really not be applicable to the pipx use case.

**Comment by itsayellow** [comment]
I agree for VCS URLs we should either ignore `--editable` or disallow it.  

I'm leaning toward the solution of just ignoring it and displaying a warning message.

**Comment by uranusjr** [comment]
Installing from VCS is essentially a shorthand of

1. Clone VCS URL to a local directory
2. `pip install` that local directory

And an editable installation differs from non-editable in two ways:

1. The URL is cloned to a predictable directory (`$VIRTUAL_ENV/src/<egg-name>` or `$PWD/src/<egg-name>` depending on whether `VIRTUAL_ENV` is defined, indicating pip is running in a virtual environment)
2. The local directory is installed in editable mode (i.e. `pip install --editable <clone directory>`)

This maps badly to pipx, in which the virtual environment is an implementation detail (I believe?), and the user should not be expected to interact with the repository in it. So there really is not a distinction between the editable mode and non-editable, aside from how the package is actually installed—which also shouldn’t make a difference, otherwise the package has a bug.

It makes sense to me to ignore `--editable` in this case with a warning.

**Comment by cs01** [comment]
> This maps badly to pipx, in which the virtual environment is an implementation detail (I believe?), and the user should not be expected to interact with the repository in it.

Some things have been creeping in which make it not an implementation detail, such as `inject`. That said, I don't really like the idea of using `--editable` at all in pipx, because pipx is for consuming applications as an end-user, not modifying them as a developer. There are plenty of other tools that do that like poetry, pipenv, tox/nox, venv, etc.

**Comment by itsayellow** [comment]
I actually really like using `--editable` for my own python utilities I make for myself.  It means that pipx can handle setting up a venv and putting all the apps in my path, and I can continue hacking on it.  And as a bonus if somebody else want to use one of my utilities, it's verified to work with pipx.

**Comment by itsayellow** [comment]
Also, I think what makes it more of an implementation detail for non-local paths is the fact that in those cases it instructs pipx to create a new `src` subdirectory in the venv.  This is probably not super useful for pipx which tries to keep the venvs tucked away out of sight.  With a local path, the user can keep their code wherever it currently resides to work on.
