### ISSUE TITLE
Instead of showing spinner, show useful install information

### ISSUE THREAD

**Issue by traverseda** [pipxproject/pipx#446]
Right now pipx hides install information, instead just showing a spinner. It would be nice if that information was instead visible, I don't really see the appeal of hiding it.

**Comment by cs01** [comment]
Add install info alongside the spinner or make the output using the ‘—verbose’ flag the default? One of the goals of pipx is to work at the right level of abstraction. When installing a package pipx generally avoids output spewing to the terminal when unnecessary.

**Comment by uranusjr** [comment]
“Useful information” is an extremely fine line to walk. pip (which is on the extreme other side of the spectrum) is critisised by many to be showing too much output, causing information fatigue. I would prefer pipx to keep its current approach, since it is much more difficult to reduce output than add it.

**Comment by traverseda** [comment]
Verbose definitely outputs a lot more information than it needs to, I think. Showing the output from `pipx > (run_subprocess:112): running /home/traverseda/.local/pipx/venvs/ytmdl/bin/python -c #!/usr/bin/env python3` is probably too much.

>When installing a package pipx generally avoids output spewing to the terminal when unnecessary.

I don't know, showing information for information's sake seems bad, but so does hiding all the nuts-and-bolts behind a facade, you know? Software is messy, and I still see anything command-line based as firmly in the tools.

    Using cached tensorflow-2.2.0-cp38-cp38-manylinux2010_x86_64.whl (516.3 MB)

If relevant information I think. Potentially very relevant if you're on a metered connection.

> is critisised by many to be showing too much output, causing information fatigue.

I really don't get that line of thought. You can *always* ignore output if you want. I see the spinner as automating the job of ignoring output? I just really don't see that perspective. If it was somehow filtering or better displaying the relevant output that would be a good thing, like if you could condense the data to show only the more relevant parts that would be great.

Just automating the task of ignoring output on the users behalf? I don't get it.

**Comment by traverseda** [comment]
@uranusjr I honestly haven't seen any of that criticism. Can you point me in that general direction?

**Comment by uranusjr** [comment]
Most of the problems are identified during the recently  conducted user experience research project. As you say, you can always ignore output if you want. Information fatigue is the phenomenon that when you show too much to users, they tend to start glossing over what they *think* is not important, and missing things that are actually relevant when they appear.

One pattern identified from the interviews by our UX researchers is that people would give feedback like “I think pip should tell me XYZ” only to later be informed those are already in the output message. What pip is currently trying to identify is what exactly are the most common cases when people would need output, and what the most helpful output in those cases.

So what I’d suggest here is for you (and other users) to instead identify concrete cases when the lack of output is actually harmful to the experience, and what output would helpwith the situation. As an example, it is extremely confusing if you `pipx install cowsay` and have the subsequent `cowsay` command fail with “command not found”. So pipx should provide output when this happens, i.e. when the directory pipx installs commands in is not in the user’s PATH.

An inverse example would be the “Using cached” message you mentioned. Do most people actively care whether a package is downloaded of installed from cache? According to our interviews, very few ever do. So that would be a message that likely shouldn’t have been added in the first place, and is a candidate for removal now.
