### ISSUE TITLE
Can't install non-PyPI package which requires system site packages

### ISSUE THREAD

**Issue by Phidica** [pipxproject/pipx#495]
Using pipx version 0.15.5.1 with Python 3.8 on Fedora 32.

**Describe the bug**
Package name cannot be determined from spec (for non-PyPI installs) when system site packages are a required dependency.

**How to reproduce**
1. Attempt to install a package which depends on a system site package. For example, `git+https://github.com/awamper/draobpilc` which depends on `gi`.
1. Run pipx as `pipx install --system-site-packages git+https://github.com/awamper/draobpilc`
1. Get result 
```
    ERROR: Command errored out with exit status 1:
     command: /tmp/tmpv1h0xjy4/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-3tj31dcw/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-3tj31dcw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-iehpn1yl
         cwd: /tmp/pip-req-build-3tj31dcw/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-3tj31dcw/setup.py", line 16, in <module>
        from draobpilc import version
      File "/tmp/pip-req-build-3tj31dcw/draobpilc/__init__.py", line 18, in <module>
        import gi
    ModuleNotFoundError: No module named 'gi'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Cannot determine package name from spec 'git+https://github.com/awamper/draobpilc'. Check package spec for errors.
```

**Expected behavior**
As far as I can tell, the problem is that in the definition of `package_name_from_spec()`, on the line https://github.com/pipxproject/pipx/blob/50dc0e929c558f6e112421a5c830bda05257d5ca/src/pipx/commands/common.py#L262 `--system-site-packages` is not passed through `venv_args` even if it was originally given by the user on the command line.
If I manually add this argument in source code and repeat the pipx install, I get the expected result
```
  installed package Draobpilc 0.3, Python 3.8.5
  These apps are now globally available
    - draobpilc
done! ✨ 🌟 ✨
```

**Comment by itsayellow** [comment]
Thanks for the great bug report.  This needs to be looked into and I will when I have some time.

**Comment by itsayellow** [comment]
The main problem is that `git+https://github.com/awamper/draobpilc` seems unable to be installed via:
`pip3 install --no-dependencies git+https://github.com/awamper/draobpilc`.   Further, it has an undeclared dependency on `gi`.

Background: If pipx can't parse the name of the package easily it first installs to a temp directory with `--no-dependencies`.  Because `draobpilc` can't be installed that way, pipx's package name determination fails.

One issue seems to be that `draobpilc` requires `gi` but that dependency isn't listed in the `install_requires` argument in `setup.py`.

The real problem seems to be that `draobpilc`'s `setup.py` has the statement at the top `from draobpilc import version
`, which triggers loading of `draobpilc/__init__.py`, which then tries to import gi, the undeclared dependency of `draobpilc`.  This means we cannot even install it (which uses `setup.py`) without the hidden `gi` dependency being needed.

If this package were fixed so that it could be installed using `pip3 install --no-dependencies` on a system with no `gi` package present, it should work with pipx.  But my opinion is that this is not a pipx problem and this Issue is a `WONTFIX` for us.

**Comment by Phidica** [comment]
Thanks for the detailed info! That makes sense. I'll open an issue against draobpilc to allow `--no-dependencies` installs.

That having been said, would it hurt for the temporary venv to know about system site packages if the user has already passed the `--system-site-packages` option? Just in case there are other Python packages which have this sort of misconfiguration? I could imagine some package maintainers might not consider it a bug that a `--no-dependencies` install doesn't work, especially if the only reason to *make* it work is to allow pipx to perform its particular fallback method of name parsing.
