### ISSUE TITLE
Issues install mssql-cli on MacOS Catalina

### ISSUE THREAD

**Issue by michaeljmcd** [pipxproject/pipx#632]
**Describe the bug**
When I attempt to install mssql-cli on macOS with Catalina, having both Python 3 and system Python (version 2.7) installed, mssql-cli errors out.

**How to reproduce**

```
$ pipx install --include-deps --verbose --python python3 mssql-cli          
pipx >(setup:704): pipx version is 0.16.0.0
pipx >(setup:705): Default python interpreter is '/usr/bin/python3'
pipx >(package_name_from_spec:299): Determined package name: mssql-cli
pipx >(package_name_from_spec:300): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:120): running python3 -m venv --without-pip /Users/michael/.local/pipx/venvs/mssql-cli
pipx >(run_subprocess:120): running /Users/michael/.local/pipx/venvs/mssql-cli/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:120): running /Users/michael/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:120): running /Users/michael/.local/pipx/venvs/mssql-cli/bin/python --version
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: mssql-cli
installing mssql-cli...
pipx >(run_subprocess:120): running /Users/michael/.local/pipx/venvs/mssql-cli/bin/python -m pip install mssql-cli
pipx >(run_subprocess:120): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:283): get_venv_metadata_for_package: 222ms
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: mssql-cli
pipx >(_symlink_package_apps:153): ⚠️  Note: pygmentize was already on your PATH at /usr/local/bin/pygmentize
pipx >(_symlink_package_apps:153): ⚠️  Note: sqlformat was already on your PATH at /usr/local/bin/sqlformat
pipx >(needs_upgrade:68): Time since last upgrade of shared libs, in seconds: 8723. Upgrade will be run by pipx if greater than 2592000.
  installed package mssql-cli 1.0.0, Python 3.7.3
  These apps are now globally available
    - futurize
    - mssql-cli
    - mssql-cli.bat
    - pasteurize
    - pygmentize
    - sqlformat
done! ✨ 🌟 ✨

> $ mssql-cli                       
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named mssqlcli

$ echo $PIPX_DEFAULT_PYTHON                                                                                                                                                                                            
python3

$ pipx list                                  
venvs are in /Users/michael/.local/pipx/venvs
apps are exposed on your $PATH at /Users/michael/.local/bin
   package mssql-cli 1.0.0, Python 3.7.3
    - futurize
    - mssql-cli
    - mssql-cli.bat
    - pasteurize
    - pygmentize
    - sqlformat
$ which python                   
/usr/bin/python

$ python --version                 
Python 2.7.16

$ which python3                
/usr/bin/python3

$ python3 --version       
Python 3.7.3
```

**Expected behavior**

Mssql-cli is able to run after being installed via `pipx`.

**Comment by itsayellow** [comment]
Can you make sure that `which mssql-cli` returns your pipx-installed mssql-cli in `~/.local/bin` with `which mssql-cli`?

It looks like when you run mssql-cli it is using Python 2.7, which judging from pipx's install is not what pipx installed for mssql-cli.  I've never seen a pipx-installed tool look for Python 2.* before, so I'm wondering if you're finding a different binary for mssql-cli

**Comment by itsayellow** [comment]
You could also try executing the full path: `~/.local/bin/mssql-cli` to see if you get the same error.

**Comment by michaeljmcd** [comment]
`which` returns the one in `~/.local/bin` (I hadn't thought to check that; just assumed that there wouldn't be another one one the PATH so it was worth checking). Running `~/.local/bin/mssql-cli` had the same outcome as `mssql-cli`.

**Comment by michaeljmcd** [comment]
Another interesting tidbit is that if I uninstall non-system versions of Python, `brew install pyenv`, use pyenv to install Python 3.9.1 and use it as the default, run `pyenv init`, use the pyenv version of pip to install pipx, use this version of pipx to install mssql-cli, I then get the same error for the correct version of Python:

```
$ mssql-cli                              
/Users/michael/.pyenv/versions/3.9.1/bin/python: Error while finding module specification for 'mssqlcli.main' (ModuleNotFoundError: No module named 'mssqlcli')
```

**Comment by itsayellow** [comment]
The problem seems to be that mssql-cli uses `scripts` in its `setup.py` instead of the more modern `entry_points`, `console_scripts` method to define its app executable.
https://github.com/dbcli/mssql-cli/blob/0fa724f740abc5c9813a879d1b295b01a8d78432/setup.py#L64

In general this is a less reliable way of defining binaries associated with the package.

In this case, the "script" that is created for mssql-cli uses this line to start itself:
```
python -m mssqlcli.main "$@"
```
Presumably because mssql-cli has its roots as a Python 2.* application, `python` gets used instead of `python3`.  Not only is this not specific to a particular venv's python, it will find your mac's Python 2.* binary, which is named `python` on a Mac.

If it mssql-cli used `console_scripts` in `setup.py`, the installed binary would instead point to the exact path of the python executable in the mssql-cli venv.

I'm not sure if there's anything pipx can do here to fix things.

mssql-cli should switch their `setup.py` to use `entry_points` `console_scripts` method of installing binaries, (NOT `scripts`.)

The workaround for you would be to go into the script for `mssql-cli` in `~/.local/bin` and replace the string `python` with the full path to the python inside the venv directory for mssql-cli, e.g. `~/.local/pipx/venvs/mssql-cli/bin/python3`

**Comment by itsayellow** [comment]
BTW, when a package uses `scripts`, the package itself supplies the script.  So in addition the exact writing of the `mssql-cli` script is due to the mssql-cli project.

I'm going to close this because there's nothing we can do, short of wait for the mssql-cli team to fix this on their side.

**Comment by michaeljmcd** [comment]
That's all fair. For anyone else who might run into this, I did get the package running with `pip` + `pyenv` (but no `pipx`).
