### ISSUE TITLE
Jupyter and bash-kernel not working

### ISSUE THREAD

**Issue by alanwilter** [pipxproject/pipx#657]
**Describe the bug**

`pipx install jupyter` works fine.
However, I use [`bash-kernel`](https://pypi.org/project/bash_kernel/), so I tried:

```
pipx inject jupyter bash-kernel --verbose
pipx >(setup:711): pipx version is 0.16.1.0
pipx >(setup:712): Default python interpreter is '/usr/local/opt/python@3.9/bin/python3.9'
pipx >(run_pipx_command:166): Virtual Environment location is $HOME/.local/pipx/venvs/jupyter
pipx >(needs_upgrade:67): Time since last upgrade of shared libs, in seconds: 67093. Upgrade will be run by pipx if greater than 2592000.
pipx >(package_name_from_spec:295): Determined package name: bash-kernel
pipx >(package_name_from_spec:296): Package name determined in 0.0s
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: bash-kernel
installing bash-kernel...
pipx >(run_subprocess:130): running $HOME/.local/pipx/venvs/jupyter/bin/python -m pip install bash-kernel
pipx >(run_subprocess:130): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:306): get_venv_metadata_for_package: 172ms
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: bash-kernel
  injected package bash-kernel into venv jupyter
done! ✨ 🌟 ✨
```
and when I did (or via browser), it failed with:
```
jupyter console --kernel bash
/usr/local/opt/python@3.9/bin/python3.9: No module named bash_kernel
...
```
Besides, though I expected to see `bash-kernel` in `pipx list`:

```
...
   package jupyter 1.0.0, Python 3.9.2
    - iptest
    - iptest3
    - ipython
    - ipython3
    - jsonschema
    - jupyter
    - jupyter-bundlerextension
    - jupyter-console
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-migrate
    - jupyter-nbconvert
    - jupyter-nbextension
    - jupyter-notebook
    - jupyter-qtconsole
    - jupyter-run
    - jupyter-serverextension
    - jupyter-troubleshoot
    - jupyter-trust
    - pygmentize
    ...
```
It's not there, however, I see:
```bash
$ ls -1d $HOME/.local/pipx/venvs/jupyter/lib/python3.9/site-packages/bash_kernel*
$HOME/.local/pipx/venvs/jupyter/lib/python3.9/site-packages/bash_kernel
$HOME/.local/pipx/venvs/jupyter/lib/python3.9/site-packages/bash_kernel-0.7.2.dist-info
```
I've installed `python3` and `pipx` via `brew` on macOS Big Sur 11.2.3.

I did the same tests above with `jupyterlab`, same issues.

**Expected behavior**

If I do `/usr/loca/bin/python3 -m pip install jupyter bash-kernel` (i.e. directly in my "global" python), all works as expected.
I can run `jupyter` and open a session using `bash` kernel.

**Comment by itsayellow** [comment]
I think this may be a quirk with jupyter.
I'm on macOS Big Sur 11.2.3 also

I can confirm this doesn't work as expected with pipx.

I can also confirm that this doesn't work with a plain python virtual environment (venv).  This probably means that the kernel mechanism for jupyter (or `bash-kernel`) has an incompatibility with running jupyter from a venv.
This sequence fails also (but should work)
```shell
python3 -m venv test_venv
source test_venv/bin/activate
pip install -U pip
pip install -U wheel
pip install jupyter
pip install bash-kernel
jupyter console --kernel bash
```

Since this also fails when pipx is not involved I'm going to assume this issue is not a pipx problem.  Let me know if there's more evidence that makes it look like pipx is involved somehow.

**Comment by itsayellow** [comment]
It looks like there's a second step to install `bash-kernel`? from https://github.com/takluyver/bash_kernel
> To install:
> ```
> pip install bash_kernel
> python -m bash_kernel.install
> ```

When I do `python -m bash_kernel.install` it works in my venv `test_venv`.

Unfortunately pipx has no method to run an arbitrary python script in one of its venvs.

As a workaround, you can do the following:
```shell
> pipx install jupyter --include-deps
  installed package jupyter 1.0.0, Python 3.9.2
  These apps are now globally available
    - iptest
    - iptest3
    - ipython
    - ipython3
    - jsonschema
    - jupyter
    - jupyter-bundlerextension
    - jupyter-console
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-migrate
    - jupyter-nbconvert
    - jupyter-nbextension
    - jupyter-notebook
    - jupyter-qtconsole
    - jupyter-run
    - jupyter-serverextension
    - jupyter-troubleshoot
    - jupyter-trust
    - pygmentize
done! ✨ 🌟 ✨
> pipx inject jupyter bash-kernel
  injected package bash-kernel into venv jupyter
done! ✨ 🌟 ✨
> ~/.local/pipx/venvs/jupyter/bin/python -m bash_kernel.install
Installing IPython kernel spec
> jupyter console --kernel bash
Jupyter console 6.4.0

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.

In [1]: 

```

If the creator of `bash-kernel` changes his pip install process so that it finishes by executing `python -m bash_kernel.install` as part of the install, you won't have to do anything special.  As it is you need to run the final install function from pipx's jupyter venv python.

**Comment by itsayellow** [comment]
Also, to see your injected `kernel-bash` use
```shell
pipx list --include-injected
```

**Comment by alanwilter** [comment]
Spectacular! Thanks for nailing this.
