### ISSUE TITLE
Security issue in pipx caused by misstyping command names

### ISSUE THREAD

**Issue by apollo13** [pipxproject/pipx#69]
Initially sent as email to @cs01, but reposting here per his request. The initial report was:

I've noticed that pipx is vulnerable to RCE if someone misstypes a command. I did type `pipx upgrade_all` out of mistake and if pypi would have had an `upgrade_all` package `pipx` would download and run it. I realize this is a "feature", but I do not think a simple typo in the command arguments like this should cause an issue. What do you think about moving `pipx BINARY` towards `pipx run BINARY`, in this case the intent is explicit and it is clearer that BINARY will download something and the changes for typos are less.

---

I realize that it is kinda weird to call this a security issue since `pipx` does download and execute software anyways, but it would be nice to guard against simple typos nevertheless.

Another option, suggested by @cs01 in our conversation, would be to add code to detect typos and then prevent execution unless `--force` (or similar) is passed. From a pure technical point I think introducing `run` would be easier and less error prone.

**Comment by adamchainz** [comment]
An implementation of this would be to use `difflib.get_close_matches` to match the typed string against the known commands, and if any of them are close enough, error.

**Comment by cs01** [comment]
I like `pipx run BINARY` because 
* it doesn't "special case" running a binary (I had to write some tricky parsing logic to make `pipx BINARY` work), so the pipx API is more consistent
* will potentially save you from running something like `pipx intsall`

I like `pipx BINARY` because
* it's less characters (easier to tell someone to run `pipx black .` than `pipx run black .`)
* matches `npx`'s API (though npx does not let you install)

That said, as apollo13 said in our emails, I suspect `pipx BINARY` is not used very often. 

So I will post a couple more comments and ask that anyone who has an opinion add a thumbs up/down based on your preferences.

**Comment by cs01** [comment]
Option 1: replace `pipx BINARY` with `pipx run BINARY`

(please vote)

**Comment by cs01** [comment]
Option 2: leave `pipx BINARY` as-is, but detect typos and then prevent execution unless `--force` (or similar) is passed

(please vote)

**Comment by cs01** [comment]
Looks like we have a winner 🎉. @apollo13 thanks for bringing this up. I will implement it.
