### ISSUE TITLE
```pipx --verbose``` falsely states that --verbose is an unrecognized argument

### ISSUE THREAD

**Issue by 62f** [pipxproject/pipx#694]
**Describe the bug**

~$ pipx --verbose
usage: pipx [-h] [--version]
            {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,completions}
            ...
pipx: error: unrecognized arguments: --verbose
**How to reproduce**

precisely ... my point exactly ...
**Expected behavior**

same thing which happens when ```pipx``` is run, or perhaps call up the pseudocode which is being run for educational purposes, maybe nothing at all (null input, null output). ANYTHING but the current patent lie!

**Comment by itsayellow** [comment]
I don't quite understand what the problem is.

pipx doesn't have a `--verbose` argument to pipx itself, only after a pipx subcommand.  In general pipx needs to be run with a sub-command, the only exceptions being `-h` or `--version` (as the help text describes.)

As is typical (and helpful) for other CLI applications, when you supply an argument to pipx that isn't accepted, it responds with a help message showing the forms of the pipx command that it will accept.

**Comment by uranusjr** [comment]
Yeah, that’s how CLI works. Git does a similar thing:

```
$ git --amend
unknown option: --amend
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

**Comment by uranusjr** [comment]
(Although I guess it could be argued `--verbose` should probably be a top-level option instead of local to each subcommand?)

**Comment by 62f** [comment]
@uranusjr So if you want to compare pipx to apples, then see here: output of ```git --html-path --verbose``` and ```git --html-path```
are identical, with no complaint from git:
/usr/share/doc/git-doc
&
/usr/share/doc/git-doc
 The tradition of hiding easter eggs behind vapid exceptions until La Caza del Día de Pascua needs to end somewhere, and so right here and now I'm finally putting my own foot down about stopping it.
